"""init db

Revision ID: 152baba18098
Revises: 
Create Date: 2023-01-14 01:48:09.964962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152baba18098'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('Flat', 'Gym', 'Pool', 'SkatingRink', 'Shooting', 'Other', 'Outdoor', name='facilitytypes'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('property_form', sa.Enum('Unknown', 'RussianFederationSubject', 'Federal', 'Municipal', 'Private', 'Other', name='facilitypropertyforms'), nullable=False),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('actual_workload', sa.Integer(), nullable=True),
    sa.Column('annual_capacity', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('converting_type', sa.Enum('Printed', 'RubberBitumen', 'RubberTile', 'Polymer', 'Synthetic', name='facilitycoveringtypes'), nullable=True),
    sa.Column('is_accessible_for_disabled', sa.Boolean(), nullable=True),
    sa.Column('paying_type', sa.Enum('FullFree', 'PartlyFree', 'NotFree', name='facilitypayingtypes'), nullable=False),
    sa.Column('who_can_use', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('open_hours', sa.String(), nullable=True),
    sa.Column('eps', sa.Integer(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__facilities')),
    sa.UniqueConstraint('name', name=op.f('uq__facilities__name'))
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('contacts', sa.String(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__feedbacks'))
    )
    op.create_table('mailings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__mailings')),
    sa.UniqueConstraint('email', name=op.f('uq__mailings__email'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('group', sa.Enum('Admin', name='usergroups'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
    sa.UniqueConstraint('email', name=op.f('uq__users__email'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('mailings')
    op.drop_table('feedbacks')
    op.drop_table('facilities')
    # ### end Alembic commands ###
