"""some migration

Revision ID: 66da39cf7d23
Revises: 152baba18098
Create Date: 2023-01-16 11:02:54.873142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66da39cf7d23'
down_revision = '152baba18098'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group', postgresql.ENUM('Admin', name='usergroups'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
