"""one more migration

Revision ID: 675d54bc47f2
Revises: 152baba18098
Create Date: 2023-01-14 05:39:47.794613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '675d54bc47f2'
down_revision = '152baba18098'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facilities', 'type',
               existing_type=postgresql.ENUM('Flat', 'Gym', 'Pool', 'SkatingRink', 'Shooting', 'Other', 'Outdoor', name='facilitytypes'),
               nullable=True)
    op.alter_column('facilities', 'property_form',
               existing_type=postgresql.ENUM('Unknown', 'RussianFederationSubject', 'Federal', 'Municipal', 'Private', 'Other', name='facilitypropertyforms'),
               nullable=True)
    op.alter_column('facilities', 'paying_type',
               existing_type=postgresql.ENUM('FullFree', 'PartlyFree', 'NotFree', name='facilitypayingtypes'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facilities', 'paying_type',
               existing_type=postgresql.ENUM('FullFree', 'PartlyFree', 'NotFree', name='facilitypayingtypes'),
               nullable=False)
    op.alter_column('facilities', 'property_form',
               existing_type=postgresql.ENUM('Unknown', 'RussianFederationSubject', 'Federal', 'Municipal', 'Private', 'Other', name='facilitypropertyforms'),
               nullable=False)
    op.alter_column('facilities', 'type',
               existing_type=postgresql.ENUM('Flat', 'Gym', 'Pool', 'SkatingRink', 'Shooting', 'Other', 'Outdoor', name='facilitytypes'),
               nullable=False)
    # ### end Alembic commands ###
