"""one more migration

Revision ID: 8631f8955fda
Revises: 675d54bc47f2
Create Date: 2023-01-14 05:42:41.445428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8631f8955fda'
down_revision = '675d54bc47f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facilities', 'hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facilities', 'hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
