"""some migration

Revision ID: ba7c33f98dd2
Revises: 66da39cf7d23
Create Date: 2023-01-16 13:06:33.927486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba7c33f98dd2'
down_revision = '66da39cf7d23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facilities', 'type',
               existing_type=postgresql.ENUM('Flat', 'Gym', 'Pool', 'SkatingRink', 'Shooting', 'Other', 'Outdoor', name='facilitytypes'),
               nullable=True)
    op.alter_column('facilities', 'property_form',
               existing_type=postgresql.ENUM('Unknown', 'RussianFederationSubject', 'Federal', 'Municipal', 'Private', 'Other', name='facilitypropertyforms'),
               nullable=True)
    op.alter_column('facilities', 'paying_type',
               existing_type=postgresql.ENUM('FullFree', 'PartlyFree', 'NotFree', name='facilitypayingtypes'),
               nullable=True)
    op.alter_column('facilities', 'hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facilities', 'hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('facilities', 'paying_type',
               existing_type=postgresql.ENUM('FullFree', 'PartlyFree', 'NotFree', name='facilitypayingtypes'),
               nullable=False)
    op.alter_column('facilities', 'property_form',
               existing_type=postgresql.ENUM('Unknown', 'RussianFederationSubject', 'Federal', 'Municipal', 'Private', 'Other', name='facilitypropertyforms'),
               nullable=False)
    op.alter_column('facilities', 'type',
               existing_type=postgresql.ENUM('Flat', 'Gym', 'Pool', 'SkatingRink', 'Shooting', 'Other', 'Outdoor', name='facilitytypes'),
               nullable=False)
    # ### end Alembic commands ###
