"""some migration

Revision ID: a2e96f4096bf
Revises: 
Create Date: 2023-01-18 14:30:00.680440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e96f4096bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('Flat', 'Gym', 'Pool', 'SkatingRink', 'Shooting', 'Other', 'Outdoor', name='facilitytypes'), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('property_form', sa.Enum('RussianFederationSubject', 'Federal', 'Municipal', 'Private', 'Other', name='facilitypropertyforms'), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('actual_workload', sa.Integer(), nullable=True),
    sa.Column('annual_capacity', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('converting_type', sa.Enum('Printed', 'RubberBitumen', 'RubberTile', 'Polymer', 'Synthetic', name='facilitycoveringtypes'), nullable=True),
    sa.Column('is_accessible_for_disabled', sa.Boolean(), nullable=True),
    sa.Column('paying_type', sa.Enum('FullFree', 'PartlyFree', 'NotFree', name='facilitypayingtypes'), nullable=True),
    sa.Column('who_can_use', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('open_hours', sa.String(), nullable=True),
    sa.Column('eps', sa.Integer(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__facility')),
    sa.UniqueConstraint('name', name=op.f('uq__facility__name'))
    )
    op.create_index('ix__facilities__id', 'facility', ['id'], unique=False, postgresql_using='hash')
    op.create_index('ix__facilities__name', 'facility', ['name'], unique=False, postgresql_using='hash')
    op.create_index('ix__facilities__x', 'facility', ['x'], unique=False, postgresql_using='btree')
    op.create_index('ix__facilities__y', 'facility', ['y'], unique=False, postgresql_using='btree')
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
    sa.UniqueConstraint('email', name=op.f('uq__users__email'))
    )
    op.create_index('ix__users__id', 'users', ['id'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix__users__id', table_name='users', postgresql_using='hash')
    op.drop_table('users')
    op.drop_index('ix__facilities__y', table_name='facility', postgresql_using='btree')
    op.drop_index('ix__facilities__x', table_name='facility', postgresql_using='btree')
    op.drop_index('ix__facilities__name', table_name='facility', postgresql_using='hash')
    op.drop_index('ix__facilities__id', table_name='facility', postgresql_using='hash')
    op.drop_table('facility')
    # ### end Alembic commands ###
