name: deploy

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: docker://postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user123
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: sportsmap_test
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt
    - name: Lint
      run: |
        cd ./api
        pylama
    - name: Test
      run: |
        cd ./api
        API_PORT="8080" \
        API_DB_URL="postgresql+asyncpg://user123:123@localhost:5432/sportsmap_test" \
        pytest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get-docker-version
        run: sh ./scripts/get-version.sh
        env:
          OAUTH: ${{ secrets.OAUTH }}
          REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
          IMAGE_NAME: sportsmap-backend-new

      - name: deploy-docker-frontend
        run: sh ./scripts/deploy.sh
        env:
          OAUTH: ${{ secrets.OAUTH }}
          REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
          VERSION: ${{ env.NEW_VERSION }}
          API_PORT: 8080
