name: deploy

on:
  workflow_run:
    branches: [ "main" ]
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get-docker-version
        run: sh ./scripts/get-version.sh
        env:
          OAUTH: ${{ secrets.OAUTH }}
          REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
          IMAGE_NAME: sportsmap-backend-new

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

      - name: migrate
        run: |
          cd ./api
          python -m db --db-url ${{ secrets.DB_URL }} upgrade head

      - name: deploy-docker-backend
        run: sh ./scripts/deploy.sh
        env:
          OAUTH: ${{ secrets.OAUTH }}
          REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
          VERSION: ${{ env.NEW_VERSION }}
          API_PORT: 8080
